# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
future: true
title: Blog Marketing
email: lantoniotrento@gmail.com
description: >
  Dive into the world of email marketing, nurturing relationships with your subscribers and converting them into loyal customers.
logo: "/assets/images/logo-nav.png"

language: en
permalink: /:title/

baseurl: "" # the subpath of your site, e.g. blog/ remember to put the / at the end
url: "https://blogmarketing.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Antonio Trento'
bio: >
  Driven by this realization, Antonio embarked on a mission to explore the intricacies of blog marketing, delving into the art of creating compelling content, optimizing for search engines, harnessing the power of social media, and mastering email marketing strategies. His unwavering dedication to learning and sharing his knowledge has earned him a reputation as a trusted guide and mentor in the blog marketing realm.
author_image: "/assets/images/author.jpg"
twitter_username: fomofoto
github_username:  antoniotrento

#The basic aside datas that will shown

aside-title: Unlock the Power of Marketing with Our Easy-to-Use Builder
aside-image: clickfunnels-optin.png
aside-description: In today's competitive digital marketing landscape, creating high-converting funnels is crucial for driving leads, boosting sales, and achieving your business objectives. However, designing and optimizing funnels can be a complex and time-consuming process. Make it easy
aside-button-link: 'https://www.clickfunnels.com/sign-up-flow?aff=e8c29a91-8f63-4931-90bd-126142888d61-1WzEwLDQ0MTAyXQ0'
aside-button-text: Discover

# Google Analytics WHEN YOU LIKE TO HOST ONLY WITH GOOLE ANALYTICS (This configuration type is more quick in 
# terms of loading if compared with the combination of tag managet/optimize/analitycs downstairs)

# uncomment to use--> 
# analytics_id: 

author :
  name : Antonio Trento
  email : lantoniotrento@gmail.com
  github : antoniotrento/antoniotrento.github.io
  twitter : lantoniotrento
  facebook: antoniotrento
  linkedin: antoniotrento
  instagram: lantoniotrento
  pinterest: lantoniotrento
  feedburner :

# MY GOOGLE MAPS FOOTER LOCATION IN ALL PAGES
location:
  latitude: 42.45999529999999
  longitude: 14.156590800000004

# WHEN YOU WANT TO HOST WITH THE COMBINATION OF GOOLE TAG MANAGER, ANALYTICS AND OPTIMIZE 
# (tracking_id, optimize_id, tagmanager_id ARE REQUIRED FIELDS)
google :
    tracking_id :  #Id google analitics
    optimize_id :  #I'id di google optimize per A/B Testing
    optimize_experiment_id: ' ' #I'id di dell'esperimento google optimize per A/B Testing
    tagmanager_id:  'GTM-PHMVZRTG'
    #ad_client:  # id google ADsense (to edit other id's of google ADsense go to /_includes/JB/ads-block-html )


# data for jekyll-seo-tags plugin
social:
  name: Antonio Trento
  links:
    - https://twitter.com/fomofoto
    - https://www.facebook.com/fomofoto
    - https://www.linkedin.com/in/antoniotrento
    - https://plus.google.com/u/0/b/114870349902392641766/105909498949786982602
    - https://github.com/fomofoto/fomofoto.github.io
    

twitter:
  username: lantoniotrento

facebook:
 app_id:  #the app id from https://developers.facebook.com/
 admins:  #the page ID from https://www.facebook.com/pg/lantoniotrento (page-link), left click about scroll down and find 'Page ID'
 publisher:  #the page ID from https://www.facebook.com/pg/lantoniotrento (page-link), left click about scroll down and find 'Page ID'
 pixel: 

 

    
# disqus :
#    short_name : jorigamy

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
  - jekyll-seo-tag

plugins:
  - jekyll-redirect-from
